function [TrainMatrix, goodness] = acbrReviewPhase(...
                                    retrieved_indexes, TrainMatrix, goodness,...
                                    current_instance, choosen_class, ...
                                    forget_option)
    % TODO!!!
end